### ISSUE TITLE
DAFLIX: Add Login Functionality

### ISSUE THREAD

**Issue by harshpatel2212** [MSTC-DA-IICT/Hacktoberfest22-dare-2-design#2]

**Comment by Aman0307** [comment]
@harshpatel2212 I would like to contribute to this issue

**Comment by harshpatel2212** [comment]
@Aman0307 Sure. Also, DAFLIX is a like a mvoie website. Here we are expecting a Home page for DAFLIX with login and Register Features. It would be great if you can show a img or any other design that you'll be using to develop the requirements.

**Comment by Amisha2004** [comment]
I would like to contribute to this issue

**Comment by harshpatel2212** [comment]
@Aman0307 Are you working on the issue. Your acceptance and some input would be requried. Please acknowledge.

**Comment by harshpatel2212** [comment]
> I would like to contribute to this issue

@Amisha2004 if Aman is not working on the issue, we'll assign it to you.

**Comment by harshpatel2212** [comment]
@Aman0307 , Please provide some updates to the issue.

**Comment by Aman0307** [comment]
@harshpatel2212 I would only be able to design a simple layout page(I know only HTML and CSS). If that is fine I will create a PR otherwise you can assign this task to someone else.

**Comment by harshpatel2212** [comment]
Yes, it would work. You may do the PR.

**Comment by harshpatel2212** [comment]
@Aman0307 You have been assigned this issue since 5 days, Can you provide some update? Otherwise I would have to assign this issue to someone else.

**Comment by Aman0307** [comment]
@harshpatel2212  Creating a PR by today evening.
