### ISSUE TITLE
DAFLIX: Add Movies List Page

### ISSUE THREAD

**Issue by harshpatel2212** [MSTC-DA-IICT/Hacktoberfest22-dare-2-design#3]

**Comment by Amisha2004** [comment]
@harshpatel2212  I would like to contribute to this issue

**Comment by harshpatel2212** [comment]
> @harshpatel2212 I would like to contribute to this issue

Okay, You can start working on the issue.

Happy Developing!

**Comment by premkumarsevugan** [comment]
I'll create the site. Will you accept the pull requests?

**Comment by harshpatel2212** [comment]
> I'll create the site. Will you accept the pull requests?

@Amisha2004, please provide some updates on the issue before midnight.  

If She fails to do so, we'll assign the issue to you

**Comment by Amisha2004** [comment]
Sorry, commit and create pull request.On Oct 9, 2022 11:13, Amisha Kumari ***@***.***> wrote:I have created basic layout. I will pull ASAP (before midnight).On Oct 9, 2022 10:51, Harsh Patel ***@***.***> wrote:

I'll create the site. Will you accept the pull requests?

@Amisha2004, please provide some updates on the issue before midnight.
If She fails to do so, we'll assign the issue to you

**Comment by Amisha2004** [comment]
![Uploading Screenshot (1244).png…]()

Can You please review if its fine.

**Comment by Amisha2004** [comment]
@harshpatel2212  Can You please tell why my pull request had been rejected??

**Comment by harshpatel2212** [comment]
> @harshpatel2212 Can You please tell why my pull request had been rejected??

Your Pull Request is merged.

**Comment by Amisha2004** [comment]
I have created basic layout. I will pull ASAP (before midnight).On Oct 9, 2022 10:51, Harsh Patel ***@***.***> wrote:

I'll create the site. Will you accept the pull requests?

@Amisha2004, please provide some updates on the issue before midnight.
If She fails to do so, we'll assign the issue to you
